image: python:3.7.4
pipelines:
  default:
    - parallel:
        - step:
            name: Unit test
            script:
              - pip install poetry
              - poetry install --extras server
              - poetry run pytest --junitxml=test-results/unit-test-results.xml tilediiif test_tilediiif
            caches:
              - pip
        - step:
            name: Integration test
            script:
              - pip install tox
              - tox
            caches:
              - pip
        - step:
            name: Lint
            script:
              - pip install flake8 black
              - >
                black --check tilediiif test_tilediiif integration_test || \
                  echo "Error: Python code has not been formatted - run 'make format-python'"
              - flake8
            caches:
              - pip
