image: python:3.7.4
pipelines:
  default:
    - parallel:
        - step:
            name: Unit test
            script:
              - pip install poetry
              - poetry install
              - poetry run pytest --junitxml=test-results/unit-test-results.xml test_tilediiif
            caches:
              - pip
        - step:
            name: Integration test
            script:
              - pip install tox
              - tox
            caches:
              - pip
        - step:
            name: Lint
            script:
              - pip install flake8
              - flake8
            caches:
              - pip
