version: "3.8"

services:
    ci:
        build:
            context: .
            dockerfile: Dockerfile
            target: tools-dev
        volumes:
            - .:/opt/tilediiif
            - venv-ci:/root/.cache/pypoetry/virtualenvs
        working_dir: /opt/tilediiif
        command: npx projen test

    tools-dev:
        build:
            context: .
            dockerfile: Dockerfile
            target: tools-dev
        volumes:
            - ./tilediiif.tools:/opt/tilediiif/tilediiif.tools
            - ./tilediiif.core:/opt/tilediiif/tilediiif.core
            - venv-tools-dev:/root/.cache/pypoetry/virtualenvs
        working_dir: /opt/tilediiif/tilediiif.tools
        command: sh -c "poetry install && poetry run pytest tests integration_tests"

    tools-dev-with-broken-mozjpeg:
        build:
            context: .
            dockerfile: Dockerfile
            target: tools-dev-with-broken-mozjpeg
        volumes:
            - ./tilediiif.tools:/opt/tilediiif/tilediiif.tools
            - ./tilediiif.core:/opt/tilediiif/tilediiif.core
            - venv-tools-dev-with-broken-mozjpeg:/root/.cache/pypoetry/virtualenvs
        working_dir: /opt/tilediiif/tilediiif.tools
        environment:
            EXPECT_MOZJPEG_SUPPORT: broken
        command: sh -c "poetry install && poetry run pytest -vv integration_tests/dzi_tiles/test_mozjpeg.py"

    tools-dev-without-mozjpeg:
        build:
            context: .
            dockerfile: Dockerfile
            target: tools-dev
            args:
                VIPS_USE_MOZJPEG:
        volumes:
            - ./tilediiif.tools:/opt/tilediiif/tilediiif.tools
            - ./tilediiif.core:/opt/tilediiif/tilediiif.core
            - venv-tools-dev-without-mozjpeg:/root/.cache/pypoetry/virtualenvs
        working_dir: /opt/tilediiif/tilediiif.tools
        environment:
            EXPECT_MOZJPEG_SUPPORT: disabled
        command: sh -c "poetry install && poetry run pytest -vv integration_tests/dzi_tiles/test_mozjpeg.py"

volumes:
    venv-ci:
    venv-tools-dev:
    venv-tools-dev-with-broken-mozjpeg:
    venv-tools-dev-without-mozjpeg:
