version: "3.8"

services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        volumes:
            - .:/opt/project
        command: pytest test_tilediiif integration_test
