[tool.poetry]
name = "tilediiif"
version = "0.1.0"
description = "Command line tools to create/manage tile-backed IIIF Image API servers"
authors = ["Hal Blackburn <hwtb2@cam.ac.uk>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
